FileName="pelagic.obj"
ScaleFactor=3.0
YCorrection=-1.4
AngleCorrection=0

Depth=3.0

HasGPS=1
HasDepthSounder=1
MaxDepth=50

Views=6

ViewX(1)=0
ViewY(1)=4.5
ViewZ(1)=1.2

ViewX(2)=0
ViewY(2)=4.5
ViewZ(2)=0.8

ViewX(3)=-1.3
ViewY(3)=4.5
ViewZ(3)=1.2

ViewX(4)=1.3
ViewY(4)=4.5
ViewZ(4)=1.2

ViewX(5)=0
ViewY(5)=6
ViewZ(5)=1.6

ViewX(6)=0
ViewY(6)=11
ViewZ(6)=-6

WheelX=0
WheelY=4
WheelZ=1.85


PortThrottleX=-2.86
PortThrottleY=28.98
PortThrottleZ=24.56

StbdThrottleX=-2.63
StbdThrottleY=28.98
StbdThrottleZ=24.56

Max_propulsion_force=4000
AsternEfficiency=0.667
Mass=7000

MaxRevs=2000

DynamicsSpeedA=18.71
DynamicsSpeedB=100

PropSpace=2.0
DynamicsTurnDragA=180000
DynamicsTurnDragB=12000
Inertia=120000
RudderA=5
RudderB=0.05
RudderBAstern=0
centrifugalDriftEffect=0.03
BlockCoefficient=0.55
maxSpeedAhead=20
PropWalkAhead=100
PropWalkAstern=300
PropWalkDriftEffect=0.000007

Buffet=3.0
Swell=0.5
Windage=0.05
WindageTurnEffect=1.3

DeviationMaximum=5
DeviationMaximumHeading=10


# -left +right
RadarScreenX=-0.54
# +up -down
RadarScreenY=4.15
# +front -back
RadarScreenZ=2.21

RadarScreenSize=0.23
